M48
; DRILL file {KiCad 7.0.9} date Thursday, January 18, 2024 at 11:01:50 AM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-01-18T11:01:50-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X117.018Y-16.637
X117.018Y-121.637
X217.018Y-16.637
X217.018Y-121.637
T0
M30
